image:
  name: docker/compose
  entrypoint: [""]
  
services:
  - docker:dind


stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "nothing to do in build stage"

test:
  stage: test
  script:
    - apt-get update
    - apt-get install python3
    - docker-compose version
    - docker-compose up &
    - sleep 10
    - echo "testing"
    - cd test
    - ./runtests.sh
