FROM node:lts-alpine

# Create app directory
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY package.json .
COPY package-lock.json .
RUN ls
RUN npm ci

# Bundle app source
COPY . .

# Exports
EXPOSE 3000
# CMD ["npm", "run", "dev"]
