FROM node:lts-alpine

# Create app directory
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY package.json .
RUN npm install

# Bundle app source
COPY . .

# Exports
EXPOSE 3000
CMD ["npm", "run", "dev"]
