# This is a basic workflow to help you get started with Actions

name: backend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ github_actions, master ]
  pull_request:
    branches: [ github_actions, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: start backend server
      run: docker-compose up -d

    # - name: install jest to execute backend tests
    #   run: npm install jest

    - name: wait for server to come up
      run: timeout 300 until curl -sf http://localhost:3000/api/v0 > /dev/null; do; echo not yet; sleep 0.5; done

    # Runs a single command using the runners shell
    - name: test backend standalone
      run: npx jest
